name: DeepThought
version: 1.0
date: 19/09/2017
description: |
    This package provides functions for computations in finitely generated nilpotent groups based on the Deep Thought algorithm.

authors:
    - name: Nina Wagner
      url: 
    - name: Max Horn
      url: http://www.quendi.de/math

maintainers:
    - name: Nina Wagner
      url: 
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">= 4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "polycyclic"
      version: ">= 2.11"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/polycyclic/"

www: https://duskydolphin.github.io/DeepThoughtPackage/
readme: README.md
packageinfo: https://duskydolphin.github.io/DeepThoughtPackage/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/duskydolphin/DeepThought/releases/download/v1.0/DeepThought-1.0.tar.gz

abstract: |
    

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
